# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./rumble-app  

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    
    - name: Install dependencies
      working-directory: ./rumble-app 
      run: npm install
      
    - name: Clean
      working-directory: ./rumble-app 
      run: npm run clean

    - name: Lint
      working-directory: ./rumble-app 
      run: npm run lint

    - name: Run the tests and generate coverage report
      working-directory: ./rumble-app 
      run: npm run test -- --coverage
      
    - name: Build
      working-directory: ./rumble-app 
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_RUMBLE_DEPLOY }}
        publish_dir: ./rumble-app/build



